name: "Release"

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
